### ISSUE TITLE
The package layout could be improved by making test/run independent from install

### ISSUE THREAD

**Issue by S4lt5** [cisagov/skeleton-python-library#106]
# 💡 Summary #

In my first experience with a skeleton-python-library application, I was perplexed by the levels of obfuscation to get to "python themodulename" / "pip install -r ..."

I believe a fairly common workflow for testing/running a python package generally involves:

* checking out the package
* launching a container to cover the specific python version required, if necessary or desired for isolation
* installing requirements
* running tests

However, in my experience, there were relative package import errors unless I both:

* added ```__main__.py``` and ```__init__.py``` to ```src/```  
* provided this path to ```PYTHONPATH``` when running the module or ```pytest```.

For what it is worth, on my development workstation the setup-env failed in the specific downstream project, and the setup.py develop also failed, so I was forced to. make these changes to develop or make changes to the app without continuously reinstalling.

When running this example, I'd expect 

```bash
python -m ./src/example 
#or
python src/example
```

to work , but any attempt to run the module from the repository directory fails with "Relative module import" or " Attempted relative import with no known parent package"  errors. This can be rectifying by creating said parent package.

## Motivation and context ##

Usability and security concerns, I believe that making the "run this app" process simpler would make adoption greater, and the ability to properly audit package contents is pretty significant.

The change was fairly minor and increased my usability of the product quite a bit in the local environment.

## Implementation notes ##

Within ```src/``` add a ```__init__.py``` and ```__main__.py``` such that the package can be run directly without installation for purposes of development, CI, testing, etc. This also requires a change to example/__init__.py to include the imported "main" method.

##  Suggested ```src/__init__.py```
```python

# Python package.
from example import main
__all__ = [
    "example","main"
]
```

## Suggested ```src/__main__.py```

```python
"""Code to run if this package is used as a Python module."""

from example import main

main()
```

# Finally, ```src/example/__init__.py``` will include the "main" module so that the parent may import it.
```python
...
from .example import example_div, main

__all__ = ["example_div","main"]
``` 

This allows for testing without installation.

## Acceptance criteria ##

- [ ] all requirements clearly defined in a requirements[-xyz].txt file
- [ ] package can be run after checkout and package installation, without requiring a full setup.py install

**Comment by jsf9k** [comment]
@Yablargo, did you try following the non-`setup-env` instructions in [CONTRIBUTING.md](https://github.com/cisagov/skeleton-python-library/blob/develop/CONTRIBUTING.md)?

@mcdonnnj, please have a look at this issue.

**Comment by S4lt5** [comment]
@jsf9k Actually, I am going to pause this, as I dive into the docs deeper I think my setup for the particular downstream project I was using was broken. 

Reading the docs, it *SHOULD* work for me, and I'm going to try to solve my particular issue and probably close this.

**Comment by jsf9k** [comment]
> @jsf9k Actually, I am going to pause this, as I dive into the docs deeper I think my setup for the particular downstream project I was using was broken.
> 
> Reading the docs, it _SHOULD_ work for me, and I'm going to try to solve my particular issue and probably close this.

OK, please keep us updated.  We are always open to hearing about how we can improve the skeletons.  Thanks for creating an issue!

**Comment by S4lt5** [comment]
Will do, I think my kneejerk reaction from an older skeleton version was "wow this is painful, why is it this way!?!?" but as I dive into the docs more (and see that snyk will indeed audit setup.py directly...), most of my problems seem like they were specific bugs.

**Comment by S4lt5** [comment]
While I was having some problems with the ```setup-env``` in my particular environment, ```setup.py develop``` worked for me in all cases, so I am going to close this, sorry for wasting everybody's time!
