### ISSUE TITLE
Unpin virtualenv when ansible/ansible-lint#590 is resolved 

### ISSUE THREAD

**Issue by felddy** [cisagov/skeleton-python-library#21]
Once https://github.com/ansible/ansible-lint/issues/590 is resolved unpin `virtualenv`:

https://github.com/cisagov/skeleton-python-library/blob/fae7694e455ce720725dcad95313f1324a9e90c4/setup.py#L77

**Comment by mcdonnnj** [comment]
This should be resolved in #23 .
