### ISSUE TITLE
LGTM bug creating false alerts: "Module imports itself".

### ISSUE THREAD

**Issue by felddy** [cisagov/skeleton-python-library#35]
# 💥 Regression Report

This issue is to track a regression in LGTM and its effects on this skeleton project and all the inheriting child projects.  

All `__init__.py` files are incorrectly being flagged with [Module imports itself](https://lgtm.com/rules/7890085/) alerts. 

These alerts can safely be ignored for now.  It is expected that the next version of LGTM will correct this behavior in the next couple of weeks.  We can expect these alerts to resolve at that time.

Please close this issue once the LGTM alerts in this project are resolved.

Example:
- https://lgtm.com/projects/g/cisagov/skeleton-python-library/alerts/?mode=list  

See: 
- https://github.com/Semmle/ql/issues/2771
- https://github.com/Semmle/ql/pull/2802

## Last working version

This is not a version-based issue. 

Worked up to date: < `2020-02-06 02:44:10`

Stopped working date: > `2020-02-06 02:44:10`

**Comment by mcdonnnj** [comment]
Closing this since we have removed the LGTM integration from the organization. We have also migrated to CodeQL per #115.
