### ISSUE TITLE
Update email address and URL in setup.py

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-python-library#57]
# 🐛 Bug Report #

* The `author_email` field listed in `setup.py` is ancient and inaccessible to the devs.  It should be updated to, say, a Trio mailing list.
* The `url` field listed in `setup.py` can probably also be updated to something more modern.

**Comment by hillaryj** [comment]
For email:
- github@cisa.dhs.gov
- cisagov-github@trio.dhs.gov
- One of the dev lists?

For URL, here are two options:
- https://us-cert.cisa.gov/ - the CISA homepage
- https://www.cisa.gov/cyber-hygiene-services - the new CyHy homepage

**Comment by dav3r** [comment]
For email, I vote for github@cisa.dhs.gov because I can't think of anything better to use.

For the URL, I vote for https://www.cisa.gov/cybersecurity - I think that is a good starting point for anyone that wants to know about CISA and cybersecurity.
