### ISSUE TITLE
Update build GHA Workflow for Newer coveralls-python Configurations

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/skeleton-python-library#70]
# 💡 Summary #

@dav3r ran into and fixed an issue with the `coveralls-python` configuration in https://github.com/cisagov/gophish-tools/pull/29 and based on the [configuration documentation for `coveralls-python`](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support) it appears that we need to update `build.yml` to reflect these adjustments.

## Motivation and context ##

Fix an apparent bug and fully support the parallelization we already use.

## Implementation notes ##

Please provide details for implementation, such as:

- Update to use `GITHUB_TOKEN` instead of `COVERALLS_REPO_TOKEN`
- Update to support the parallelization we use to test all supported Python versions.

## Acceptance criteria ##

- [ ] Actions run successfully using the new secret value.
- [ ] Parallel jobs are correctly flagged to help checking possible changes between Python versions.

**Comment by dav3r** [comment]
@mcdonnnj Thanks for putting in this issue! 👍
