### ISSUE TITLE
Test is incomplete

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-python-library#79]
# 💡 Summary #

Flesh out the `test_log_levels()` test function so that it verifies that the correct log level has been assigned.

## Motivation and context ##

As it stands, `test_log_levels()` would still pass if `example.example.main()` set the log level to `DEBUG` no matter what command-line arguments were passed to it..

See the discussion [here](https://github.com/cisagov/pe-reports/pull/6#discussion_r657329612).

## Acceptance criteria ##

- [x] `test_log_levels()` verifies that the log level is assigned correctly.

**Comment by mcdonnnj** [comment]
Nice catch in the fallible nature of that test.
