### ISSUE TITLE
B

### ISSUE THREAD

**Issue by nickfnblum** [cisagov/skeleton-python-library#84]
# 💡 Summary #

What is the work, as a high-level summary?

## Motivation and context ##

Why does this work belong in this project?

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by jsf9k** [comment]
Closing this issue to to a complete lack of content.
